# config/meta.yml

meta_product_name: "Cogito"
meta_title: "T-Each"
meta_description: "Ease your Students homeworks, Improve your teaching"
meta_image: "http://www.rawstory.com/wp-content/uploads/2014/03/students-laughing-at-something-on-phone-on-shutterstock-800x430.jpg"
