# config/meta.yml

meta_product_name: "Cogito"
meta_title: "Cogito cards"
meta_description: "Boost your students learning confidence by sharing them your own quizzes"
meta_image: "http://www.rawstory.com/wp-content/uploads/2014/03/students-laughing-at-something-on-phone-on-shutterstock-800x430.jpg"
