# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: b3cc57968307aaae800c8c177f8ec96b4c74de8b0ab58a7bc9411cbf7d94ca035302fcb132a878f2555d5fec7a7ea2a49c2de4e29c840c80138cae7f70da6263

test:
  secret_key_base: f6454d3de750ec449198e45b716aaf6172150bc82fd773d23cec46f2bc86f3adff5b0fbdba5ae733b730b8ce70ae94f2cafb8adccc991d4482b9dc4fd929d6fc

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
